### ISSUE TITLE
Game minimizing/black screen while the server client is open.

### ISSUE THREAD

**Issue by TheYakubi** [RainwayApp/bug-tracker#91] opened 2018-01-22 21:02 UTC
Hello, just wanted to report a weird bug I found. Whenever I play Warframe, the game has a tendency to minimize itself or give me a black screen while the Rainway App is open in the background. I'm not sure if this is an issue with other games but if it is, it could cause a lot of negative feedback so I thought I'd report this real quick.

**Comment by healingbrew** [comment] 2018-01-23 19:41
Duplicate of #19

**Closed by healingbrew** 2018-01-23 19:41 UTC
