### ISSUE TITLE
New Feature: A button to directly start a desktop session

### ISSUE THREAD

**Issue by olivieralvespro** [RainwayApp/bug-tracker#111] opened 2018-01-24 11:39 UTC
When we start a game and an error happened there is a possibility to start a desktop session.

I would like to have this option directly present if possible somewhere on the client, would be great to have  this option for people like me who develop a lot on their computer and not just gaming ;)

**Comment by BetaLeaf** [comment] 2018-01-24 13:31
I second this!

**Comment by BetaLeaf** [comment] 2018-01-24 13:46
Until proper support is implemented, I made my own solution.

Add Desktop Mode.exe included in the ZIP file as a Non-Steam game, then restart Rainway. 
If Desktop Mode doesn't appear in your list of games on Rainway, then delete Rainway cache.

How to add a Non-Steam game: https://support.steampowered.com/kb_article.php?ref=2219-YDJV-5557

To exit desktop mode, open the Rainway overlay and select exit game.

Source Code is included. Open the Desktop Mode.au3 in SciTE included with AutoIt3 or via Notepad. (all it does is sleeps for an hour which loops indefinitely)

[Desktop Mode.zip](https://github.com/RainwayApp/bug-tracker/files/1660027/Desktop.Mode.zip)

**Comment by Jessomadic** [comment] 2018-01-24 14:42
I mean that is one way to do it. Or you could just add IE as one and that works too

**Comment by BetaLeaf** [comment] 2018-01-24 14:43
You have to keep IE open else the session closes. My version doesn't have this requirement. It just runs silently in the background and you use the Rainway overlay to end the session when you want to.

**Comment by Jessomadic** [comment] 2018-01-24 14:45
I might have to try this then. At work right now. I will try when I get home

**Comment by healingbrew** [comment] 2018-01-24 18:09
Duplicate of #63

**Closed by healingbrew** 2018-01-24 18:09 UTC
