### ISSUE TITLE
panel.pond not found!?

### ISSUE THREAD

**Issue by KrisPCream** [RainwayApp/bug-tracker#23] opened 2018-01-21 04:36 UTC
everytime i try to launch the app it does nothing for about 3 or 4 mins. Then a little error pop up comes up saying it can find a thing and keeps popping up over and over.

![image](https://user-images.githubusercontent.com/31629049/35190880-835b7b06-fe21-11e7-89e6-71b861fd8d7e.png)

it wont launch rainway and just keeps saying that

**Comment by Zenexer** [comment] 2018-01-21 06:33
Uninstall Rainway, download a fresh copy, and reinstall it.  This looks like a bug that might've been fixed.  You're receiving the error because Rainway is trying to access `%UserProfile%` from a process running under the `SYSTEM` account.

**Comment by Codeusa** [comment] 2018-01-21 06:52
This was resolved in the latest update, this was caused by users being flagged by cloudfront.

**Comment by origamiwhale** [comment] 2018-01-21 12:38
Hey @Zenexer, sadly I'm experiencing the same issue on Rainway build 0.1.5
My error message looks exactly like the @KrisPCream 's.

Tried uninstalling and reinstalling, as well as `Checking for updates`.

If you need any other debug info I'll be happy to provide it.

Cheers,

**Comment by Codeusa** [comment] 2018-01-21 16:08
@origamiwhale go to 

C:\Windows\System32\config\systemprofile\AppData\Roaming\RainwayInc\Radar

And provide me the Radar.log file

**Comment by origamiwhale** [comment] 2018-01-21 16:47
Here it is
https://pastebin.com/9B9gyRFJ

cheers,

**Comment by origamiwhale** [comment] 2018-01-23 23:06
@healingbrew , @Codeusa just letting you guys know that on latest build (0.1.13) this issue doesn't occur any longer on my machine 👌🏻

**Comment by healingbrew** [comment] 2018-01-25 03:03
Issue has returned apparently.

**Comment by Codeusa** [comment] 2018-01-25 05:43
This is caused by anti-virus blocking our CDN. Because its the same place our installer is hosted and they think its a virus.

**Comment by healingbrew** [comment] 2018-01-25 06:54
🤔

**Closed by healingbrew** 2018-01-25 06:54 UTC
Labels: fixed but not closed, installer, server

**Comment by March-happy** [comment] 2018-03-09 15:01
Still appear. I wonder where's the panel.pond because some CDN services like AWS is quite slow and may be blocked in Mainland China.
