### ISSUE TITLE
How to get a dns?

### ISSUE THREAD

**Issue by awesomehd1** [RainwayApp/bug-tracker#22] opened 2018-01-21 04:20 UTC
Continued 

The title said it all

but how would i get a dns?

**Comment by Jbbrack03** [comment] 2018-01-21 04:26
DNS is a service provided by your ISP by default. It's usually passed along by your router. Restarting your Router and Modem might help. You can also go into your Network Settings in Windows and setup your own DNS Servers.

**Comment by awesomehd1** [comment] 2018-01-21 04:44
so can i switch the wifi?

**Comment by trilleplay** [comment] 2018-01-21 17:45
There is soooo many things wrong with your reasoning there @awesomehd1

**Comment by healingbrew** [comment] 2018-01-23 19:24
Duplicate of #16.

**Closed by healingbrew** 2018-01-23 19:24 UTC
