### ISSUE TITLE
Suggestion - make a invite link to play a friend's steam list

### ISSUE THREAD

**Issue by animekai** [RainwayApp/bug-tracker#138] opened 2018-01-30 15:45 UTC
Making a way to play someone else steam games via streaming, like an invitation link, or friend list allowed to share the games streaming

**Comment by Jessomadic** [comment] 2018-01-30 17:10
I mean that would be more on steam's side. Easy way to do that is to set up Family Sharing for the games. They are added to your Game Library  so in theory they would show up in Rainway. Sidenote: Change Suggestion to "Enhancement"

**Comment by animekai** [comment] 2018-02-01 06:55
But playing from others streaming list would be great, as my friend could share me a link to play in his rainway server a especific game from his steam library, or other people who has better internet speed for streaming

**Comment by healingbrew** [comment] 2018-02-26 16:47
Duplicate of #110

**Closed by healingbrew** 2018-02-26 16:47 UTC
