### ISSUE TITLE
Scaling Issue with Firefox and Windows

### ISSUE THREAD

**Issue by JTTM** [RainwayApp/bug-tracker#98] opened 2018-01-23 06:49 UTC
When you use a smaller laptop screen that has a high resolution like 1080p then it's usually scalled in Windows Settings. In my example I am at 1080p and 150% scale. 

Depending on the set resolution for streaming some weird things will happen in Firefox. At 1920x1080 streaming to my laptop the image is very small, but if I zoom out (not zoom in) then the image gets bigger until 50% zoom where it's normal sized. At 1280x720 streaming the image is normal sized at 100% zoom. This issue only occurs within Firefox.

Display settings:
<img width="960" alt="ecbx58" src="https://user-images.githubusercontent.com/14990787/35264740-f428926e-ffc1-11e7-80af-6baee990d5f3.png">

1080p Steam at 100% Zoom:
<img width="960" alt="i2b3py" src="https://user-images.githubusercontent.com/14990787/35264806-3a414b2e-ffc2-11e7-907d-8e53bf2f9110.png">
Full Screen:
<img width="960" alt="firefox_2018-01-22_22-14-31" src="https://user-images.githubusercontent.com/14990787/35264818-44452db6-ffc2-11e7-8878-22763ea4defb.png">

1080p Steam at 50% Zoom:
<img width="960" alt="firefox_2018-01-22_22-11-28" src="https://user-images.githubusercontent.com/14990787/35264836-52139cf2-ffc2-11e7-8514-be0f73def9cb.png">

720p Steam at 100% Zoom (Full Screen):
<img width="960" alt="firefox_2018-01-22_22-15-01" src="https://user-images.githubusercontent.com/14990787/35264855-620059fc-ffc2-11e7-9839-7ba4e089190b.png">

**Comment by healingbrew** [comment] 2018-01-23 19:44
Duplicate of #18 (albeit with more info)

**Closed by healingbrew** 2018-01-23 19:44 UTC
