### ISSUE TITLE
Doom (2016) gets detected as Doom 3 in the client

### ISSUE THREAD

**Issue by TheJanzap** [RainwayApp/bug-tracker#126] opened 2018-01-25 18:00 UTC
Banner image and description are from Doom 3 and not from Doom (2016).
Game starts and plays normally though.

**Comment by Jessomadic** [comment] 2018-01-25 22:40
They are working on it

**Comment by Jessomadic** [comment] 2018-01-25 22:40
Just close it

**Comment by healingbrew** [comment] 2018-01-30 11:36
Closed as partial duplicate of #14

**Closed by healingbrew** 2018-01-30 11:36 UTC
Labels: meta
