### ISSUE TITLE
Rainway doesn't see my steam games.

### ISSUE THREAD

**Issue by mixon606** [RainwayApp/bug-tracker#132] opened 2018-01-27 15:12 UTC
Rainway can't see my steam games
![rainwaykurwa steama nje widzi](https://user-images.githubusercontent.com/35871306/35473218-c67ee0ac-037c-11e8-9928-b3fe2fffdd84.PNG)

**Comment by Codeusa** [comment] 2018-01-27 19:39
Does clicking the refresh button at the top help?

**Comment by mixon606** [comment] 2018-01-27 19:40
no

**Comment by fofwisdom** [comment] 2018-01-29 01:45
No.

**Comment by rmogstad** [comment] 2018-01-29 17:57
Same for me.  Clicking refresh does not help, clearing cache does not help.

**Comment by healingbrew** [comment] 2018-01-30 11:39
Duplicate of #120

**Closed by healingbrew** 2018-01-30 11:39 UTC
