### ISSUE TITLE
[Server App] Error Loading UI after first start after installation

### ISSUE THREAD

**Issue by gui007duktn** [RainwayApp/bug-tracker#59] opened 2018-01-21 22:58 UTC
After Installation , the server app don't start and after start manually, i have this message:

**Error Loading UI**
Cannot find user interface data.
(C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\RainwayInc\Server\panel.pond)

I have a song (for exemple plug a usb) before this message and a disconnect/unplug song after close this message and i have this again and again.
Reinstall app and delete folders in /%appdata%/, /Program Files/ don't change problem.

I need help, Thank you in advance.

(PS:Sorry for my english, i'm french ^^)

_OS Version : Windows 10 Version 1709_
_Version App installer: 0.1.5_

**Comment by healingbrew** [comment] 2018-01-23 19:35
Duplicate of #23

**Closed by healingbrew** 2018-01-23 19:35 UTC
Labels: bug, server
