### ISSUE TITLE
Suggestion: Add "stream desktop without game" feature

### ISSUE THREAD

**Issue by Phasedragon** [RainwayApp/bug-tracker#63] opened 2018-01-22 00:05 UTC
Automatic game detection is finicky. To be fair, that's not really a fault of rainway, it's very tough to do and nobody has done it perfectly. Just let us navigate to our games ourselves through the way we've always done it, by using the desktop. This would also allow you to actually use the remote computer, instead of having to constantly go back to it to install games and manage it.

**Comment by toothsaw** [comment] 2018-01-22 12:40
They already have an app to do that, it’s called Ulterius. Rainway should be streamlined just for streaming games.

**Comment by Jessomadic** [comment] 2018-01-22 14:18
In the future there are plans to be able to install games right from Rainway

**Comment by Jbbrack03** [comment] 2018-01-22 19:02
I don’t mind having a launcher and detection system, but if we are going that route, there should be an option to correct exe locations and manually add games that aren’t detected. For example, Rainway detects GTA 5 on my system, but links to the wrong exe which causes a social club error. Being able to correct this by pointing to the correct exe would be helpful.

**Comment by JTTM** [comment] 2018-01-24 03:12
@Jbbrack03 that would be #50 

@Phasedragon what I did was add something internet explorer as a non-steam game and rename it to remote desktop, this shows up in the rainway game list and I can run it just fine.

**Comment by BetaLeaf** [comment] 2018-01-24 18:10
Until proper support is implemented, I made my own solution.

Add Desktop Mode.exe included in the ZIP file as a Non-Steam game, then restart Rainway.
If Desktop Mode doesn't appear in your list of games on Rainway, then delete Rainway cache.

How to add a Non-Steam game: https://support.steampowered.com/kb_article.php?ref=2219-YDJV-5557

To exit desktop mode, open the Rainway overlay and select exit game.

Source Code is included. Open the Desktop Mode.au3 in SciTE included with AutoIt3 or via Notepad. (all it does is sleeps for an hour which loops indefinitely)

[Desktop Mode.zip](https://github.com/RainwayApp/bug-tracker/files/1660027/Desktop.Mode.zip)

**Comment by healingbrew** [comment] 2018-01-24 18:13
We actually do plan to eventually have support for this standard, however for now-- whatever solution you may have I suggest using the name "Remote Desktop" as we have a dummy "game" metadata entry for that name.

**Comment by JTTM** [comment] 2018-01-24 19:47
yes what @healingbrew said, I discovered that day one, was about to comment it actually

**Comment by TheMulti0** [comment] 2019-01-04 16:01
@healingbrew Since that is a relatively simple thing to do, is it already solved in Rainway 1.0.0?

**Comment by JTTM** [comment] 2019-01-04 20:58
@healingbrew Please close this issue. It was confirmed by Andrew to be added in 1.0. 
![screenshot_20190104-105412](https://user-images.githubusercontent.com/14990787/50710657-a298fd80-100f-11e9-94f2-a4ebf1780d90.png)

**Closed** 2019-01-04 21:09 UTC
Labels: enhancement
