### ISSUE TITLE
Debug mode - server won't start.

### ISSUE THREAD

**Issue by TristisOris** [RainwayApp/bug-tracker#216] opened 2018-03-29 08:40 UTC
#reproduce:

activate Debug mode in tray 
got message "Rainway will now restart."

after that app closing forever. i can't run in manualy.
v.0.2.54

**Comment by TristisOris** [comment] 2018-03-29 10:58
i reinstalled rainway. problem is not gone.
where settings store?

**Comment by TristisOris** [comment] 2018-03-29 13:37
solved.
server don't work when & **after** RDP session. what's the problem?

1. turn on PC remotely 2. turn on rainway via RDP 3. got nothing.

**Comment by Codeusa** [comment] 2018-04-01 01:31
@healingbrew can you look into a work around for this

**Comment by healingbrew** [comment] 2018-04-01 03:36
duplicate of #9

**Closed by healingbrew** 2018-04-01 03:36 UTC
Labels: bug
