### ISSUE TITLE
[Suggestion] Remote co-op play

### ISSUE THREAD

**Issue by Migushthe2nd** [RainwayApp/bug-tracker#160] opened 2018-02-05 10:44 UTC
A way to start some sort of party which multiple friends can join so they can see you screen. This way we would be able to play local co-op games remotely. I know this is not priority at the moment but I would use this a lot.

**Comment by Migushthe2nd** [comment] 2018-02-05 10:47
Now I'm just letting a single friend start a game remotely and sharing my pc audio via Skype. I can't use rainway audio share because the other would hear himself talking. Maybe it's possible to add some sort of audio filter to filter specific programs like Discord or Skype?

**Comment by Codeusa** [comment] 2018-02-05 16:01
We're are building a dedicated co-op feature.

**Comment by healingbrew** [comment] 2018-02-26 16:47
Duplicate of #110

**Closed by healingbrew** 2018-02-26 16:47 UTC
